# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j7QzXINJ9MixwbMKJl8BgvaGw5Px3LvO
"""

import time

users=[{"name":"Ahmesd","balance":123,"pincode":1234}
      ,{"name":"mohmmed","balance":123,"pincode":1244},
      {"name":"Ali","balance":123,"pincode":1254}
      ,{"name":"Mohmoud","balance":123,"pincode":1264}
      ,{"name":"oamr","balance":123,"pincode":1274}
      ,{"name":"amr","balance":123,"pincode":1284},
      {"name":"seiad","balance":123,"pincode":1294},
      {"name":"hassom","balance":123,"pincode":1235},
      {"name":"haassan","balance":123,"pincode":1236},
      {"name":"Rehab","balance":123,"pincode":1237}]

currentuser={}
currentpincode=0

def load(t):
  for i in range(1,t):
    print("\rloading"+"."*i,end=" ")
    time.sleep(1)

def intitialScreen():
  global currentpincode
  global currentuser
  found =False
  load(10)
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*               Welcome to Rehab ATM                            *")
  print("*                     please enter your                         *")
  print("*                     4-digit pin code                          *")
  currentpincode=int(input("                           "))
  print("*                                                               *")
  print("*                                                               *")
  print("*****************************************************************")
  print("*****************************************************************")
  for user in users:
    if user['pincode']==currentpincode:
      currentuser=user
      found=True
    if found:

      selectScreen()
    else:
      errorScreen()


  return 
      
def errorScreen():
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*                                                               *")
  print("*                                                               *")
  print("*               Welcome to Rehab ATM                            *")
  print("*                          ERROR                                *")
  print("*                                                               *")
  print("*                                                               *")
  print("*                                                               *")
  print("*****************************************************************")
  print("*****************************************************************")
  load(5)
  intitialScreen()
  return 
def selectScreen():
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*                                                               *")
  print("*                                                               *")
  print("*               Welcome to Rehab ATM                            *")
  print("*                 " ,currentuser['name'],"                      *")
  print("*                                                               *")
  print("*  1.cach withrowal                                             *")
  print("*  2.Balance Inquiry                                            *")
  print("*  3.Transfer                                                   *")
  print("*  Enter required operation [1,2,3,4,5,6]                       *")
  op=int(input())
  print("*****************************************************************")
  print("*****************************************************************")  
  if op==1:
    chachwithrole()
  elif op==2:
    banaceInQue()
  elif op==3:
    Transfer()
  else:
    errorScreen()

  return 
def chachwithrole():
  global currentuser
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*                                                               *")
  print("*                                                               *")
  print("*               Welcome to Rehab ATM                            *")
  print("*               please insert money required                    *")
  print("*                                                               *")
  print("*                                                               *")
  print("*                                                               *")
  amount=int(input("                            "))
  print("*****************************************************************")
  print("*****************************************************************")
  if amount <= currentuser['balance']:
    currentuser['balance']=currentuser['balance']-amount
    banaceInQue()
  else:
   errorScreen()


  return
def banaceInQue():
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*                                                               *")
  print("*                                                               *")
  print("*               Welcome to Rehab ATM                            *")
  print("*                        Balance",currentuser['balance'] ,"     *")
  print("*                                                               *")
  print("*                                                               *")
  print("*                                                               *")
  print("*****************************************************************")
  print("*****************************************************************")
  load(5)
  selectScreen()
  return
def Transfer(): 
  print("\r*****************************************************************")
  print("*****************************************************************")
  print("*                                                               *")
  print("*                                                               *")
  print("*               Welcome to Rehab ATM                            *")
  print("*               please insert money required                    *")
  print("*                                                               *")
  print("*                                                               *")
  print("*                                                               *")
  amount=int(input("    Enter the person name         "))
  print("*****************************************************************")
  print("*****************************************************************")
  if amount <= currentuser['balance']:
    for user in users:
      if(name.lower()==user["name"].lower()):
        user["balance"]= user["balance"]+amount
        currentuser['balance']=currentuser['balance']-amount
      banaceInQue()
  else:
    errorScreen()
  return

intitialScreen()